conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_aarch64: azure
build_platform:
  linux_ppc64le: linux_64
  osx_arm64: osx_64
test: native_and_emulated
bot:
  automerge: true
